name: build

on:
  push:
    branches:
      - '**'
    paths:
      - '**/*.rs'
      - '**/*.toml'
  pull_request:
    paths:
      - '**/*.rs'
      - '**/*.toml'

jobs:
  install-cross:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 50
      - uses: XAMPPRocky/get-github-release@v1
        id: cross
        with:
          owner: rust-embedded
          repo: cross
          matches: ${{ matrix.platform }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v1
        with:
          name: cross-${{ matrix.platform }}
          path: ${{ steps.cross.outputs.install_path }}
    strategy:
      matrix:
        platform: [ linux-musl, apple-darwin ]

  windows:
    runs-on: windows-latest
    needs: install-cross
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50
      - run: scripts/set_rust_version.bash ${{ matrix.channel }} ${{ matrix.target }}
        shell: bash
      - run: scripts/build.bash cargo ${{ matrix.target }}
        shell: bash
      - run: scripts/test.bash cargo ${{ matrix.target }}
        shell: bash

    strategy:
      matrix:
        channel: [ stable, beta ]
        target:
          - x86_64-pc-windows-gnu
          - x86_64-pc-windows-msvc

  macos:
    runs-on: macos-latest
    needs: install-cross
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50

      - uses: actions/download-artifact@v1
        with:
          name: cross-apple-darwin
          path: /usr/local/bin/

      - run: chmod +x /usr/local/bin/cross

      - run: scripts/set_rust_version.bash ${{ matrix.channel }} ${{ matrix.target }}
      - run: scripts/build.bash cross ${{ matrix.target }}
        # Only test on macOS platforms since we can't simulate the others.
      - run: scripts/test.bash cross ${{ matrix.target }}
        if: matrix.target == 'x86_64-apple-darwin'

    strategy:
      matrix:
        channel: [ stable, beta ]
        target:
          # macOS
          - x86_64-apple-darwin

  linux:
    runs-on: ubuntu-latest
    needs: install-cross
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 50

      - name: Download Cross
        uses: actions/download-artifact@v1
        with:
          name: cross-linux-musl
          path: /tmp/
      - run: chmod +x /tmp/cross
      - run: scripts/set_rust_version.bash ${{ matrix.channel }} ${{ matrix.target }}
      - run: scripts/build.bash /tmp/cross ${{ matrix.target }}
      - run: scripts/test.bash /tmp/cross ${{ matrix.target }}
        if: |
          !contains(matrix.target, 'android') &&
          !contains(matrix.target, 'bsd') &&
          !contains(matrix.target, 'solaris') &&
          matrix.target != 'armv5te-unknown-linux-musleabi' &&
          matrix.target != 'sparc64-unknown-linux-gnu'

    strategy:
      matrix:
        channel: [ stable, beta ]
        target:
          # Linux
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
